### ISSUE TITLE
How to transfer the data from LAFAN1 to the json or pkl file?

### ISSUE THREAD

**Issue by motor-x** [xupei0610/CompositeMotion#1]
Hi,

I am very interesting this excellent work. Could you please let me know how to transfer the data from LAFAN1 to the [json](https://github.com/xupei0610/CompositeMotion/blob/main/assets/motions/locomotion/lafan1_run1_subject5_160_2105_mirror.json) or [pkl](https://github.com/xupei0610/CompositeMotion/blob/main/assets/motions_binary/locomotion/crouch_lafan1_walk3_subject5_2490_2735_mirror.pkl) file?

Thank you!

**Comment by xupei0610** [comment]
The json file records the the global translation and rotation of the root link, and the local rotation of each link related to its parent. All rotations are recorded as quaternion in xyzw order, which is consistent with Isaacgym. You can easily transfer data from LAFAN1 by retargeting.

**Comment by motor-x** [comment]
Thank you so much for your reply!  **It would be greatly appreciate if you could share your retargeting code.** As I am using your entire repo (e.g., the data and the body in the isaacgym) and need more data from LaFAN, I would like to guarantee the consistency on the retargeting process. 

Thank you, again!
